name: Branch fast-forward-ness checker

description: Greet someone

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  head-branch-ref:
    description: '${{ github.head_ref }}'
    required: true
  base-branch-ref:
    description: '${{ github.base_ref }}'
    required: true
    
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
    
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: git fetch
      shell: bash
    - run: git merge-base origin/${{ inputs.base-branch-ref }} origin/${{ inputs.head-branch-ref }} --is-ancestor
      shell: bash
      
