on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: Test
        uses: ViRGiL175/check-branch-fast-forward-ness@main
        with:
          base-branch-ref: ${{ github.base_ref }}
          head-branch-ref: ${{ github.head_ref }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
        
